### ISSUE TITLE
Api work broken

### ISSUE THREAD

**Issue by krim** [grosser/youtube_search#13]
Youtube move API to v3. So gem not work.

> YoutubeSearch.search('lolcats').first['video_id']
> OpenURI::HTTPError: 410 Gone

**Comment by grosser** [comment]
Not using it atm, please open a PR to fix it

**Comment by illtellyoulater** [comment]
"Certain older YouTube apps will no longer be supported after April 2015" -> https://support.google.com/youtube/answer/6098135?hl=en

"Alternative for gdata.youtube.com/feeds/api/videos" -> http://stackoverflow.com/questions/30685625/alternative-for-https-gdata-youtube-com-feeds-api-videos-video-idv-2

**Comment by grosser** [comment]
yes, they block the old api, try to bump to new api

**Comment by grosser** [comment]
-> change the code and see if it works / make a PR

**Comment by illtellyoulater** [comment]
I'm sorry but I don't have enough time to rewrite the entire gem with new API support..
I'm currenly taking a look at this: https://github.com/Fullscreen/yt
